# Generated by Django 2.1.2 on 2018-12-01 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('wins', models.IntegerField(default=0, verbose_name='Wins')),
                ('losses', models.IntegerField(default=0, verbose_name='Losses')),
                ('draws', models.IntegerField(default=0, verbose_name='Draws')),
                ('seed', models.IntegerField(default=0, verbose_name='Seed')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treeSeed', models.IntegerField(default=0)),
                ('winner', models.IntegerField(choices=[(0, 'No Winner'), (1, 'First Entrant Winner'), (2, 'Second Entrant Winner')], default=0, verbose_name='Winner')),
                ('firstEntrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Entrant')),
                ('parentMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tournament.Match')),
                ('secondEntrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Entrant')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentName', models.CharField(max_length=200, verbose_name='Tournament Name')),
                ('publishDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('lastUpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('tournamentType', models.CharField(choices=[('SE', 'Single Elimination'), ('DE', 'Double Elimination'), ('RR', 'Round-Robin'), ('SW', 'Swiss')], default='SE', max_length=2, verbose_name='Tournament Type')),
                ('numberOfEntrants', models.IntegerField(default=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
    ]
