# Generated by Django 2.1.2 on 2018-12-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20181201_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
