# Generated by Django 2.1.2 on 2018-12-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20181202_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='treeSeed',
            new_name='depth',
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(choices=[(0, 'No Winner'), (1, 'First Entrant Winner'), (2, 'Second Entrant Winner'), (3, 'Draw')], default=0, verbose_name='Winner'),
        ),
    ]
