# Generated by Django 2.1.2 on 2018-12-04 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20181204_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='parentMatch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tournament.Match'),
        ),
    ]
