# Generated by Django 2.1.2 on 2018-12-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20181204_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='firstEntrant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Entrant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='secondEntrant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.Entrant'),
        ),
    ]
