# Generated by Django 2.1.2 on 2018-12-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='completed',
            new_name='matchComplete',
        ),
    ]
