# Generated by Django 2.1.2 on 2018-12-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20181205_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(choices=[(0, 'No Winner'), (1, 'First Entrant Winner'), (2, 'Second Entrant Winner'), (3, 'Draw'), (4, 'Bye')], default=0, verbose_name='Winner'),
        ),
    ]
