# Generated by Django 2.1.2 on 2018-12-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20181205_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='matchComplete',
        ),
    ]
