# Generated by Django 2.1.2 on 2018-12-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_match_matchcomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='currentRound',
            field=models.IntegerField(default=0),
        ),
    ]
